# -*- coding: utf-8 -*-
"""settings.pyの修正版

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LNcW0CR5BAEAwRx82HcB4X0bAUEXq7p
"""

from os import environ

# セキュリティ設定
SECRET_KEY = '5238389471112'
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = environ.get('OTREE_ADMIN_PASSWORD') or 'Ryoko0903'

# 実験の設定
SESSION_CONFIGS = [
    dict(
        name='mpl_japanese_session',
        display_name="MPL 日本語版",
        num_demo_participants=1,
        app_sequence=['mpl_japanese']
    ),
 dict(
        name='publiclottery_session',
        display_name="Public Lottery (dev)",
        num_demo_participants=3,
        app_sequence=['publiclottery']
    ),
    # もし他にも動かしたいゲームがあれば、ここに同じ形式で追加できます
]

# デフォルト設定
SESSION_CONFIG_DEFAULTS = dict(
    real_world_currency_per_point=1.00,
    participation_fee=0.00,
    doc=""
)

# フィールド設定
PARTICIPANT_FIELDS = []
SESSION_FIELDS = []

# 言語と通貨（日本円にする場合は 'ja' と 'JPY' に変更も可能です）
LANGUAGE_CODE = 'ja'
REAL_WORLD_CURRENCY_CODE = 'JPY'
USE_POINTS = True

# 部屋の設定
ROOMS = [
    dict(
        name='econ101',
        display_name='Econ 101 class',
    ),
    dict(name='live_demo', display_name='Room for live demo'),
]

INSTALLED_APPS = ['otree']

DEMO_PAGE_INTRO_HTML = """
Here are some oTree games."""