# -*- coding: utf-8 -*-
"""settings.py縺ｮ菫ｮ豁｣迚・
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LNcW0CR5BAEAwRx82HcB4X0bAUEXq7p
"""

from os import environ

# 繧ｻ繧ｭ繝･繝ｪ繝・ぅ險ｭ螳・SECRET_KEY = '5238389471112'
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = environ.get('OTREE_ADMIN_PASSWORD') or 'Ryoko0903'

# 螳滄ｨ薙・險ｭ螳・SESSION_CONFIGS = [
    dict(
        name='mpl_japanese_session',
        display_name="MPL 譌･譛ｬ隱樒沿",
        num_demo_participants=1,
        app_sequence=['mpl_japanese']
    ),
 dict(
        name='publiclottery_session',
        display_name="Public Lottery (dev)",
        num_demo_participants=3,
        app_sequence=['publiclottery']
    ),
    # 繧ゅ＠莉悶↓繧ょ虚縺九＠縺溘＞繧ｲ繝ｼ繝縺後≠繧後・縲√％縺薙↓蜷後§蠖｢蠑上〒霑ｽ蜉縺ｧ縺阪∪縺・]

# 繝・ヵ繧ｩ繝ｫ繝郁ｨｭ螳・SESSION_CONFIG_DEFAULTS = dict(
    real_world_currency_per_point=1.00,
    participation_fee=0.00,
    doc=""
)

# 繝輔ぅ繝ｼ繝ｫ繝芽ｨｭ螳・PARTICIPANT_FIELDS = []
SESSION_FIELDS = []

# 險隱槭→騾夊ｲｨ・域律譛ｬ蜀・↓縺吶ｋ蝣ｴ蜷医・ 'ja' 縺ｨ 'JPY' 縺ｫ螟画峩繧ょ庄閭ｽ縺ｧ縺呻ｼ・LANGUAGE_CODE = 'ja'
REAL_WORLD_CURRENCY_CODE = 'JPY'
USE_POINTS = True

# 驛ｨ螻九・險ｭ螳・ROOMS = [
    dict(
        name='econ101',
        display_name='Econ 101 class',
    ),
    dict(name='live_demo', display_name='Room for live demo'),
]

INSTALLED_APPS = ['otree', 'mpl_japanese', 'publiclottery']

DEMO_PAGE_INTRO_HTML = """
Here are some oTree games."""
